<?php
/**
 * Created by PhpStorm.
 * User: zhangshuai
 * Date: 18-3-20
 * Time: 下午3:18
 */

namespace app\common;


class RedisModel extends \yii\redis\ActiveRecord
{
  public function attributes()
  {
      parent::attributes(); // TODO: Change the autogenerated stub
  }
}