<?php
/**
 * Created by PhpStorm.
 * User: zhangshuai
 * Date: 18-4-15
 * Time: 上午9:16
 */

namespace app\models;


use PhpOffice\PhpSpreadsheet\Reader\IReadFilter;

class Xlsx extends \PhpOffice\PhpSpreadsheet\Reader\Xlsx
{
  public function __construct()
  {
      parent::__construct();
  }

  public function setReadFilter(IReadFilter $pValue)
  {
      $this->readFilter = $pValue;
      //return parent::setReadFilter($pValue); // TODO: Change the autogenerated stub
  }
}